### ISSUE TITLE
Use config() instead of env() helper

### ISSUE THREAD

**Issue by aggunawan** [poteto-dev/laravel-ui-stisla#15]
Based on this [article](https://laravel.com/docs/8.x/configuration#configuration-caching). When we cache all configuration use `config:cache` command, `env()` method will return null.

I found direct call to `env()` method at blade file eg. skeleton.blade.php.

Can we replace `env()` with `config()` method ? or we have better reason why we need to stick with `env()` ?

**Comment by muhajirinlpu** [comment]
no,  we don't have any reason for that, feel free to pull request
