### ISSUE TITLE
Use proper layout for auth

### ISSUE THREAD

**Issue by evaleries** [poteto-dev/laravel-ui-stisla#17]
Instead of using **app.blade.php** on authentication, why don't we use the existing **auth.blade.php** layout?
![image](https://user-images.githubusercontent.com/48923153/97979889-841a0e00-1e02-11eb-8513-e6287869c517.png)

**Comment by rizkyyangpalsu** [comment]
Of course, we add **auth.blade.php** for authentication layout. But, now we don't have authentication layout like **Login, Register, Forgot Password etc**. I'm so happy if you want contribute that.
