### ISSUE TITLE
  Command "ui" is not defined

### ISSUE THREAD

**Issue by ruslanashaari** [poteto-dev/laravel-ui-stisla#20]
Hi. I install laravel, run `composer install`, `npm install `and `composer require poteto-dev/laravel-ui-stisla --dev`.

Then I run `php artisan ui stisla`.

I got `Command "ui" is not defined.` 

Is there any other steps I missed? Thanks.

**Comment by rizkyyangpalsu** [comment]
Can you screenshot that error? I've been following steps like you and successful

**Comment by ruslanashaari** [comment]
Weird. Nevermind. I found another repo with Laravel 8 + Stisla + Jetstream already integrated, so I use that instead. 

Thanks for your attention.
