### ISSUE TITLE
fix icon align center when compact navigation

### ISSUE THREAD

**Issue by abu-abbas** [poteto-dev/laravel-ui-stisla#9]
please remove margin-right for fix icon align center when compact navigation

source:  resources/sass/theme/_layout.scss
line: 418

**Comment by rizkyyangpalsu** [comment]
Hello, @abu-abbas thanks to creating an issue. If you have some problems with Style/Javascript you can create an issue to [Stisla](https://github.com/stisla/stisla/issues) repository
